// This file is auto-generated by scripts/build-guides.ts
export interface UseCase {
  id: string;
  description: string;
  category: string;
}

export const USE_CASES: UseCase[] = [
  {
    "id": "content-vis",
    "description": "Improve initial page load and interaction responsiveness by deferring the rendering work of off-screen components until they are needed.",
    "category": "performance"
  }
];
