// This file is auto-generated by scripts/build-guides.ts
export interface UseCase {
  id: string;
  description: string;
  category: string;
  featuresUsed: string[];
}

export const USE_CASES: UseCase[] = [
  {
    "id": "accessible-error-announcement",
    "description": "Synchronize programmatic accessibility states (like aria-invalid) with the visual :user-invalid state to ensure screen reader users receive error feedback only after interaction, mirroring the visual experience.",
    "category": "accessibility",
    "featuresUsed": [
      ":user-valid and :user-invalid"
    ]
  },
  {
    "id": "autofill-address-form",
    "description": "Build an address form with correct autocomplete attributes and autofill support.",
    "category": "forms",
    "featuresUsed": [
      ":autofill"
    ]
  },
  {
    "id": "autofill-highlight-inputs",
    "description": "Use CSS to highlight form fields that have been autofilled by the browser and not edited by the user.",
    "category": "forms",
    "featuresUsed": [
      ":autofill"
    ]
  },
  {
    "id": "autofill-payment-form",
    "description": "Build a payment form that collects card details with correct autocomplete values and autofill support.",
    "category": "forms",
    "featuresUsed": [
      "enterkeyhint",
      "Email, telephone, and URL <input> types",
      "inputmode"
    ]
  },
  {
    "id": "autofill-sign-in-form",
    "description": "Build a sign-in form with correct autocomplete values and autofill support.",
    "category": "forms",
    "featuresUsed": [
      "Email, telephone, and URL <input> types",
      "inputmode"
    ]
  },
  {
    "id": "autofill-sign-up-form",
    "description": "Build a sign-up form with correct autocomplete values and autofill support.",
    "category": "forms",
    "featuresUsed": [
      "Email, telephone, and URL <input> types",
      "inputmode"
    ]
  },
  {
    "id": "form-fields-automatically-fit-contents",
    "description": "Allow form fields to grow and shrink to fit the user input, e.g. as the user types or selects a different option. Apply maximum and minimum size limits to create dynamic and responsive form fields that conform with the page design.",
    "category": "forms",
    "featuresUsed": [
      "field-sizing"
    ]
  },
  {
    "id": "required-field-feedback",
    "description": "Provide error message for required form fields that were skipped or left empty *only* after user interaction, to avoid preemptive errors and ensure feedback is timely and contextually relevant to the user's flow.",
    "category": "forms",
    "featuresUsed": [
      ":user-valid and :user-invalid"
    ]
  },
  {
    "id": "select-menu-interaction",
    "description": "Validate that a non-default option has been chosen in a select menu only after the user has interacted with the control.",
    "category": "forms",
    "featuresUsed": [
      ":user-valid and :user-invalid"
    ]
  },
  {
    "id": "validate-input-after-interaction",
    "description": "Show form field validation feedback (e.g. password complexity or email format requirements) only after the user has finished their initial interaction, avoiding premature errors on page load or while the user is typing.",
    "category": "forms",
    "featuresUsed": [
      ":user-valid and :user-invalid"
    ]
  },
  {
    "id": "batch-analytics-events",
    "description": "Debounce and batch multiple analytics events together in a single beacon to minimize network contention and reduce server load, while still delivering real-time updates.",
    "category": "performance",
    "featuresUsed": [
      "fetchLater",
      "AbortController and AbortSignal"
    ]
  },
  {
    "id": "conditional-async-dependencies",
    "description": "Conditionally load or initialize async dependencies (such as importing polyfills for missing web features) without requiring complex orchestration across all of a page's script dependencies.",
    "category": "performance",
    "featuresUsed": [
      "Top-level await"
    ]
  },
  {
    "id": "defer-rendering-heavy-content",
    "description": "Reduce rendering times in content-heavy web pages (e.g. pages with long feeds, lots of articles, or complex dashboards), by deferring rendering for any content that is not immediately visible to the user.",
    "category": "performance",
    "featuresUsed": [
      "hidden=\"until-found\"",
      "content-visibility"
    ]
  },
  {
    "id": "deprioritize-background-fetches",
    "description": "Deprioritize background data fetches made with the Fetch API to prevent network contention with user-initiated requests.",
    "category": "performance",
    "featuresUsed": [
      "Fetch priority",
      "Fetch"
    ]
  },
  {
    "id": "full-session-analytics",
    "description": "Reliably track analytics, errors, and telemetry data across the user's entire page visit, and defer sending of the data until the user leaves the page.",
    "category": "performance",
    "featuresUsed": [
      "fetchLater",
      "AbortController and AbortSignal"
    ]
  },
  {
    "id": "identify-heavy-scripts",
    "description": "Identify the scripts most responsible for long animation frames",
    "category": "performance",
    "featuresUsed": [
      "Long animation frames"
    ]
  },
  {
    "id": "identify-inp-causes",
    "description": "Identify slow running JavaScript that is impacting INP metric",
    "category": "performance",
    "featuresUsed": [
      "Long animation frames"
    ]
  },
  {
    "id": "improve-next-page-load-performance",
    "description": "Improve page load performance by prefetching or prerendering pages that the user is likely to visit next.",
    "category": "performance",
    "featuresUsed": [
      "Speculation rules"
    ]
  },
  {
    "id": "optimize-image-priority",
    "description": "Optimize the loading priority of Largest Contentful Paint (LCP) candidate images and deprioritize non-critical images to reduce critical resource load delays.",
    "category": "performance",
    "featuresUsed": [
      "Fetch priority"
    ]
  },
  {
    "id": "optimize-preload-priority",
    "description": "Optimize the relative priority of preloaded content to reduce critical resource load delays.",
    "category": "performance",
    "featuresUsed": [
      "Fetch priority",
      "<link rel=\"preload\">"
    ]
  },
  {
    "id": "optimize-script-priority",
    "description": "Optimize the loading priority of scripts by boosting critical asynchronous scripts and deprioritizing non-essential or late-body scripts to improve sequencing and reduce delays.",
    "category": "performance",
    "featuresUsed": [
      "Fetch priority"
    ]
  },
  {
    "id": "adapt-scrollbar-to-contrast-preferences",
    "description": "Enhance scrollbar visibility for users who prefer high-contrast interfaces",
    "category": "user-experience",
    "featuresUsed": [
      "scrollbar-color",
      "prefers-contrast media query"
    ]
  },
  {
    "id": "adapt-scrollbar-to-light-dark-preferences",
    "description": "Ensure the scrollbar visually matches the user's operating system light/dark mode preference",
    "category": "user-experience",
    "featuresUsed": [
      "scrollbar-color",
      "color-scheme",
      "prefers-color-scheme media query"
    ]
  },
  {
    "id": "animate-scrollbar-color-on-scroll",
    "description": "Animate the scrollbar color dynamically as the user scrolls down the page",
    "category": "user-experience",
    "featuresUsed": [
      "scrollbar-color",
      "Scroll-driven animations",
      "Registered custom properties"
    ]
  },
  {
    "id": "customize-scrollbar-color-and-thickness",
    "description": "Customize the color or thickness of a scrollbar",
    "category": "user-experience",
    "featuresUsed": [
      "scrollbar-color",
      "scrollbar-width"
    ]
  },
  {
    "id": "search-hidden-content",
    "description": "Hide content from view using patterns such as accordions, tabs, and \"Read more\" sections, while ensuring the hidden text reveals itself during native \"Find in page\" searches, allows search engine indexing, supports URL fragment deep links, and maintains ARIA accessibility.",
    "category": "user-experience",
    "featuresUsed": [
      "<details>",
      "Mutually exclusive <details> elements",
      "hidden=\"until-found\""
    ]
  },
  {
    "id": "style-parent-with-has",
    "description": "Style parent elements of a form field (e.g. labels or fieldsets) when the field is invalid.",
    "category": "user-experience",
    "featuresUsed": [
      ":user-valid and :user-invalid"
    ]
  }
];
